name: 'my Debian package'
description: 'Yet another "Build my Debian package" GitHub Action'
author: 'deogracia'
inputs: 
  myInput:
    description: 'Input to use'
    default: 'world'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.myInput }}
